### ISSUE TITLE
Problem Launching Weka in OS X High Sierra, Mojave

### ISSUE THREAD

**Issue by marshki** [Waikato/weka-trunk#1]
When attempting to launch the Weka 3.8.3 application from a GUI in both High Sierra and Mojave, the icon for the app will briefly appear in OS X's dock, then disappear. One can, however, launch the app successfully with: `java -jar /Applications/weka-3-8-3-oracle-jvm.app/Contents/Java/weka.jar`. Alternatively, one could navigate to the path via Finder and launch that application. 

In: `/var/log/system.log` there's an error that indicates a problem with the launcher. 

Others have noted this issue [here](http://weka.8497.n7.nabble.com/Weka-3-8-3-Does-Not-Open-on-MacOS-Mojave-td44425.html) and [here](https://stackoverflow.com/questions/54699377/weka-will-not-open-on-macos).

**Comment by fracpete** [comment]
Can you post that error?

**Comment by marshki** [comment]
I receive this error after launching the app from the GUI: 

`Apr  4 08:44:09 10-17-119-171 kcm[1128]: DEPRECATED USE in libdispatch client: Setting timer interval to 0 requests a 1ns timer, did you mean FOREVER (a one-shot timer)?`

Thanks.

**Comment by eibe** [comment]
We have identified the issue with the WEKA 3.8.3 and WEKA 3.9.3 applications for the Mac that, for many users, caused them to fail to start up via double-clicking.

On December 13, we replaced weka-3-8-3-oracle-jvm.dmg and weka-3-9-3-oracle-jvm.dmg on SourceForge with a new .dmg compatible with older versions of OS X, based on the HFS+ file system. Unfortunately, this new “release" included a pre-17 December 2018 version of the Amazon Corretto JVM 1.8.0_192 instead of the Oracle Java VM we had used before. Unfortunately, that particular version of Amazon’s Corretto had a bug on Macs:

"The libfontmanager in Corretto is linked to the libfreetype in X11 and breaks when X11 is not installed."

See https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/change-log.html.

We never noticed this problem and could not reproduce it because if, like us, you had XQuartz installed, or the libfreetype.dylib library was installed on your Mac via Homebrew, the WEKA application still worked in spite of this bug.

We have reproduced the problematic behaviour by removing XQuartz and Homebrew on one of our Macs. And, indeed, the WEKA macOS application no longer started when the bird was double-clicked.

We have just made new “releases” of the WEKA 3.8.3 .dmg and the WEKA 3.9.3 for the Mac that use the latest version of Corretto 8 (8.212.04.2). You can find these .dmg files at

https://sourceforge.net/projects/weka/files/weka-3-8/3.8.3/

and

https://sourceforge.net/projects/weka/files/weka-3-9/3.9.3/

respectively.

They are called

weka-3-8-3-corretto-jvm.dmg

and

weka-3-9-3-corretto-jvm.dmg

respectively.

We have also replaced the links for the Mac applications on the main WEKA downloads page at

https://www.cs.waikato.ac.nz/ml/weka/downloading.html
